
  @baseUrl = http://localhost:3000

  ####
GET {{baseUrl}}/v1/lesson
Content-Type: application/json
tenantid: tenanta
traceparent: 12345
Authorization: bearer Token

 ####
  # @name CreateLesson

POST {{baseUrl}}/v1/lesson
Content-Type: application/json
tenantid: tenanta
traceparent: 12345
Authorization: bearer Token

{
  "Name": "",
  "Quiz": "",
  "FillBlanks": "",
  "TrueFalse": "",
  "subject": 0
}

### Capture Id from Response
@studentId = {{CreateLesson.response.body.Id}}

####
GET {{baseUrl}}/v1/lesson/{{studentId}}
Content-Type: application/json
tenantid: tenanta
traceparent: 12345
Authorization: bearer Token

####
PUT {{baseUrl}}/v1/lesson/{{studentId}}
Content-Type: application/json
tenantid: tenanta
traceparent: 12345
Authorization: bearer Token

{
  "Name": "",
  "Quiz": "",
  "FillBlanks": "",
  "TrueFalse": "",
  "subject": 0
}

####
DELETE {{baseUrl}}/v1/lesson/{{studentId}}
Content-Type: application/json
tenantid: tenanta
traceparent: 12345
Authorization: bearer Token
