--
-- PostgreSQL database dump
--

\restrict BtcAmEdxVpLHtkbRXL6aU79Iax8J5xicBsY2e3xJ3KjCHD4sJj80ZoT92u8UYTy

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tenanta; Type: SCHEMA; Schema: -; Owner: root
--

CREATE SCHEMA tenanta;


ALTER SCHEMA tenanta OWNER TO root;

--
-- Name: enum_logindetail_role; Type: TYPE; Schema: tenanta; Owner: root
--

CREATE TYPE tenanta.enum_logindetail_role AS ENUM (
    'admin',
    'principal',
    'teacher',
    'student',
    'parent'
);


ALTER TYPE tenanta.enum_logindetail_role OWNER TO root;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: lesson; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lesson (
    "Id" integer NOT NULL,
    path character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    subject integer NOT NULL
);


ALTER TABLE tenanta.lesson OWNER TO root;

--
-- Name: lesson_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."lesson_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."lesson_Id_seq" OWNER TO root;

--
-- Name: lesson_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."lesson_Id_seq" OWNED BY tenanta.lesson."Id";


--
-- Name: lessonsection; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lessonsection (
    "Id" integer NOT NULL,
    name character varying(255) NOT NULL,
    path character varying(255) NOT NULL,
    "lessoninfoId" integer,
    "quizId" integer,
    "fillblanksId" integer,
    "truefalseId" integer,
    "shortquestionId" integer,
    subject integer NOT NULL,
    lesson integer NOT NULL
);


ALTER TABLE tenanta.lessonsection OWNER TO root;

--
-- Name: lessonsection_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

ALTER TABLE tenanta.lessonsection ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tenanta."lessonsection_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessonsection_fillblanks; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lessonsection_fillblanks (
    "Id" integer NOT NULL,
    path character varying(255) NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE tenanta.lessonsection_fillblanks OWNER TO root;

--
-- Name: lessonsection_fillblanks_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

ALTER TABLE tenanta.lessonsection_fillblanks ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tenanta."lessonsection_fillblanks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessonsection_lessoninfo; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lessonsection_lessoninfo (
    "Id" integer NOT NULL,
    path character varying(255) NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE tenanta.lessonsection_lessoninfo OWNER TO root;

--
-- Name: lessonsection_lessoninfo_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

ALTER TABLE tenanta.lessonsection_lessoninfo ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tenanta."lessonsection_lessoninfo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessonsection_quiz; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lessonsection_quiz (
    "Id" integer NOT NULL,
    path character varying(255) NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE tenanta.lessonsection_quiz OWNER TO root;

--
-- Name: lessonsection_quiz_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

ALTER TABLE tenanta.lessonsection_quiz ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tenanta."lessonsection_quiz_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessonsection_shortquestion; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lessonsection_shortquestion (
    "Id" integer NOT NULL,
    path character varying(255) NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE tenanta.lessonsection_shortquestion OWNER TO root;

--
-- Name: lessonsection_shortquestion_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

ALTER TABLE tenanta.lessonsection_shortquestion ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tenanta."lessonsection_shortquestion_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessonsection_truefalse; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.lessonsection_truefalse (
    "Id" integer NOT NULL,
    path character varying(255) NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE tenanta.lessonsection_truefalse OWNER TO root;

--
-- Name: lessonsection_truefalse_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

ALTER TABLE tenanta.lessonsection_truefalse ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tenanta."lessonsection_truefalse_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logindetail; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.logindetail (
    "Id" integer NOT NULL,
    name character varying(255) NOT NULL,
    adhaar character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role tenanta.enum_logindetail_role NOT NULL
);


ALTER TABLE tenanta.logindetail OWNER TO root;

--
-- Name: logindetail_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."logindetail_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."logindetail_Id_seq" OWNER TO root;

--
-- Name: logindetail_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."logindetail_Id_seq" OWNED BY tenanta.logindetail."Id";


--
-- Name: progress; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.progress (
    "Id" integer NOT NULL,
    quiz integer NOT NULL,
    fillblanks integer NOT NULL,
    truefalse integer NOT NULL,
    school integer NOT NULL,
    standard integer NOT NULL,
    student integer NOT NULL,
    subject integer,
    lesson integer,
    lessonsection integer
);


ALTER TABLE tenanta.progress OWNER TO root;

--
-- Name: progress_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."progress_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."progress_Id_seq" OWNER TO root;

--
-- Name: progress_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."progress_Id_seq" OWNED BY tenanta.progress."Id";


--
-- Name: school; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.school (
    "Id" integer NOT NULL,
    name character varying(255) NOT NULL,
    address character varying(255) NOT NULL
);


ALTER TABLE tenanta.school OWNER TO root;

--
-- Name: school_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."school_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."school_Id_seq" OWNER TO root;

--
-- Name: school_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."school_Id_seq" OWNED BY tenanta.school."Id";


--
-- Name: schoolstandard; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.schoolstandard (
    "Id" integer NOT NULL,
    school integer NOT NULL,
    standard integer NOT NULL
);


ALTER TABLE tenanta.schoolstandard OWNER TO root;

--
-- Name: schoolstandard_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."schoolstandard_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."schoolstandard_Id_seq" OWNER TO root;

--
-- Name: schoolstandard_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."schoolstandard_Id_seq" OWNED BY tenanta.schoolstandard."Id";


--
-- Name: standard; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.standard (
    "Id" integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE tenanta.standard OWNER TO root;

--
-- Name: standard_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."standard_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."standard_Id_seq" OWNER TO root;

--
-- Name: standard_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."standard_Id_seq" OWNED BY tenanta.standard."Id";


--
-- Name: standardsubject; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.standardsubject (
    "Id" integer NOT NULL,
    standard integer NOT NULL,
    subject integer NOT NULL
);


ALTER TABLE tenanta.standardsubject OWNER TO root;

--
-- Name: standardsubject_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."standardsubject_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."standardsubject_Id_seq" OWNER TO root;

--
-- Name: standardsubject_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."standardsubject_Id_seq" OWNED BY tenanta.standardsubject."Id";


--
-- Name: student; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.student (
    "Id" integer NOT NULL,
    name character varying(255) NOT NULL,
    adhaar character varying(255) NOT NULL,
    school integer NOT NULL,
    standard integer NOT NULL
);


ALTER TABLE tenanta.student OWNER TO root;

--
-- Name: student_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."student_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."student_Id_seq" OWNER TO root;

--
-- Name: student_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."student_Id_seq" OWNED BY tenanta.student."Id";


--
-- Name: subject; Type: TABLE; Schema: tenanta; Owner: root
--

CREATE TABLE tenanta.subject (
    "Id" integer NOT NULL,
    path character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE tenanta.subject OWNER TO root;

--
-- Name: subject_Id_seq; Type: SEQUENCE; Schema: tenanta; Owner: root
--

CREATE SEQUENCE tenanta."subject_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tenanta."subject_Id_seq" OWNER TO root;

--
-- Name: subject_Id_seq; Type: SEQUENCE OWNED BY; Schema: tenanta; Owner: root
--

ALTER SEQUENCE tenanta."subject_Id_seq" OWNED BY tenanta.subject."Id";


--
-- Name: lesson Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lesson ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."lesson_Id_seq"'::regclass);


--
-- Name: logindetail Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.logindetail ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."logindetail_Id_seq"'::regclass);


--
-- Name: progress Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."progress_Id_seq"'::regclass);


--
-- Name: school Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.school ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."school_Id_seq"'::regclass);


--
-- Name: schoolstandard Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.schoolstandard ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."schoolstandard_Id_seq"'::regclass);


--
-- Name: standard Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standard ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."standard_Id_seq"'::regclass);


--
-- Name: standardsubject Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standardsubject ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."standardsubject_Id_seq"'::regclass);


--
-- Name: student Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.student ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."student_Id_seq"'::regclass);


--
-- Name: subject Id; Type: DEFAULT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.subject ALTER COLUMN "Id" SET DEFAULT nextval('tenanta."subject_Id_seq"'::regclass);


--
-- Data for Name: lesson; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lesson ("Id", path, name, subject) FROM stdin;
1	ZY.T01.L01	Fundamental of Operating Systems	1
\.


--
-- Data for Name: lessonsection; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lessonsection ("Id", name, path, "lessoninfoId", "quizId", "fillblanksId", "truefalseId", "shortquestionId", subject, lesson) FROM stdin;
2	Threading Concepts and Execution	ZY.T01.L01.S02	\N	\N	\N	\N	\N	1	1
3	Process vs. Thread Comparison	ZY.T01.L01.S03	\N	\N	\N	\N	\N	1	2
4	Synchronization and Concurrency Challenges	ZY.T01.L01.S04	\N	\N	\N	\N	\N	1	3
5	Advanced Concurrency Techniques	ZY.T01.L01.S05	\N	\N	\N	\N	\N	1	4
1	Process Management Fundamentals	ZY.T01.L01.S01	1	1	1	1	1	1	1
\.


--
-- Data for Name: lessonsection_fillblanks; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lessonsection_fillblanks ("Id", path, data) FROM stdin;
1	ZY.T01.L01.S01	[{"answer": "process management", "question": "The fundamentals of **_____** in operating systems revolve around the execution of independent programs.", "explanation": "Process management is the core concept that oversees how programs (processes) run independently on a system.", "answer_embedding": null}, {"answer": "memory space", "question": "A process is a program in execution, characterized by its own **_____**, file descriptors, and system resources.", "explanation": "Memory space ensures isolation and security by preventing interference between processes.", "answer_embedding": null}, {"answer": "process state transitions", "question": "Key concepts in process management include **_____**, where processes move between active, blocked, ready, and terminated states.", "explanation": "State transitions define how processes change phases (e.g., running, waiting) under OS control.", "answer_embedding": null}, {"answer": "process synchronization", "question": "To prevent race conditions, processes use mechanisms like **_____**, semaphores, and mutex locks.", "explanation": "Synchronization ensures coordinated execution by managing shared resources safely.", "answer_embedding": null}, {"answer": "sockets", "question": "Advanced IPC techniques, such as pipes, shared memory, and **_____**, enable data exchange between processes.", "explanation": "Sockets allow inter-process communication over networks, enabling distributed systems.", "answer_embedding": null}]
\.


--
-- Data for Name: lessonsection_lessoninfo; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lessonsection_lessoninfo ("Id", path, data) FROM stdin;
1	ZY.T01.L01.S01	{"summary": ["Process management is how computers handle different tasks running at the same time, like each task getting its own space and resources.", "When a task starts, the computer assigns things like memory and CPU time, and it can pause or stop if needed."], "examples": ["When you’re playing a video game and your mom opens her email on the same computer, both games are like different chefs cooking at the same time—each needs its own space to run smoothly.", "Think of a busy restaurant where servers (processes) take orders (tasks) from different tables (memory). If two servers try to serve the same dish at once, they use a system where only one can serve at a time (like a lock) to avoid chaos."], "paragraph": null, "explanation": "Imagine your computer is like a big kitchen where chefs (tasks) are cooking different dishes (programs). Each chef has their own table (memory), oven (CPU), and pots (resources). When one chef finishes, the kitchen manager (computer) decides who gets to cook next or if they need to wait. To keep things fair, they use rules like taking turns (Round Robin) or giving priority to important dishes. If two chefs try to cook the same food at the same time, they use special tools (like locks) to avoid messes (conflicts)."}
\.


--
-- Data for Name: lessonsection_quiz; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lessonsection_quiz ("Id", path, data) FROM stdin;
1	ZY.T01.L01.S01	[{"answer": "Distinct memory space and isolation", "options": ["Shared memory space", "Static execution", "Distinct memory space and isolation", "Same CPU allocation"], "question": "What is the primary characteristic that distinguishes a process from a program?", "explanation": "A process is an instance of a program in execution with its own memory space, ensuring isolation and security from other processes.", "answer_embedding": null}, {"answer": "Blocked", "options": ["Ready", "Running", "Blocked", "Terminated"], "question": "Which process state represents a process waiting for an I/O operation to complete?", "explanation": "The blocked state indicates a process is waiting for an external event, such as I/O completion, before resuming execution.", "answer_embedding": null}, {"answer": "Semaphores", "options": ["Shared memory", "Semaphores", "Priority scheduling", "Pipes"], "question": "What mechanism is used to synchronize processes and prevent race conditions?", "explanation": "Semaphores are synchronization tools that control access to shared resources, ensuring orderly execution and avoiding race conditions.", "answer_embedding": null}, {"answer": "Round Robin", "options": ["Priority-based", "FCFS (First-Come-First-Served)", "Round Robin", "Multilevel Feedback Queue"], "question": "Which scheduling algorithm assigns CPU time in a round-robin fashion?", "explanation": "Round Robin allocates CPU time in fixed time slices, ensuring fair and cyclic process execution.", "answer_embedding": null}, {"answer": "To enable data exchange between processes", "options": ["To share CPU time", "To enable data exchange between processes", "To manage process termination", "To allocate memory dynamically"], "question": "What is the primary purpose of inter-process communication (IPC) techniques like pipes?", "explanation": "IPC mechanisms like pipes allow processes to communicate and share data efficiently, facilitating collaboration in multi-tasking systems.", "answer_embedding": null}]
\.


--
-- Data for Name: lessonsection_shortquestion; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lessonsection_shortquestion ("Id", path, data) FROM stdin;
1	ZY.T01.L01.S01	[{"answer": "A process is a running instance of a program with its own memory space, file descriptors, and allocated system resources, ensuring isolation and security.", "question": "What are the key characteristics that define a process as distinct from a program?", "answer_embedding": null}, {"answer": "The OS manages a process’s lifecycle through stages like creation, execution, suspension, and termination, allocating resources dynamically during these phases.", "question": "How does the operating system manage the lifecycle of a process?", "answer_embedding": null}, {"answer": "Processes transition between active (running), blocked (waiting), ready (queued), and terminated states; scheduling algorithms like Round Robin or Priority-based are used to manage these transitions.", "question": "What are the primary process state transitions, and which scheduling algorithm is commonly used to govern them?", "answer_embedding": null}, {"answer": "Process synchronization relies on mechanisms such as semaphores, mutex locks, and message passing to coordinate execution and avoid conflicts.", "question": "What mechanisms are used for process synchronization to prevent race conditions and deadlocks?", "answer_embedding": null}, {"answer": "IPC techniques like pipes and shared memory allow processes to share data securely and efficiently, enabling seamless communication in multi-tasking systems.", "question": "How do inter-process communication (IPC) techniques like pipes and shared memory enable data exchange between independent processes?", "answer_embedding": null}]
\.


--
-- Data for Name: lessonsection_truefalse; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.lessonsection_truefalse ("Id", path, data) FROM stdin;
1	ZY.T01.L01.S01	[{"answer": "False", "options": ["True", "False"], "question": "A process is the same as a program in its static form."}, {"answer": "True", "options": ["True", "False"], "question": "Each process has its own separate memory space for isolation and security."}, {"answer": "False", "options": ["True", "False"], "question": "Processes transition between states like active, blocked, and terminated without the involvement of scheduling algorithms."}, {"answer": "True", "options": ["True", "False"], "question": "Semaphores are a mechanism used to prevent race conditions in process synchronization."}, {"answer": "True", "options": ["True", "False"], "question": "Pipes are an example of inter-process communication (IPC) that allows data exchange between processes without shared memory."}]
\.


--
-- Data for Name: logindetail; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.logindetail ("Id", name, adhaar, password, role) FROM stdin;
1	admin	1111-1111-1111	admin	admin
2	teacher	2222-2222-2222	teacher	teacher
3	Yusuf Shaikh	2222-2222-2220	student	student
4	principal	4444-4444-4444	principal	principal
5	Affan Ansari	5555-5555-5550	student	student
6	Zainab Shaikh	5555-5555-5551	student	student
7	Mehndi Shaikh	5555-5555-5553	student	student
\.


--
-- Data for Name: progress; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.progress ("Id", quiz, fillblanks, truefalse, school, standard, student, subject, lesson, lessonsection) FROM stdin;
\.


--
-- Data for Name: school; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.school ("Id", name, address) FROM stdin;
1	Saboo Siddik Polytechnic	Police Lane, Nagpada, Mumbai 400008
\.


--
-- Data for Name: schoolstandard; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.schoolstandard ("Id", school, standard) FROM stdin;
2	1	1
3	1	2
\.


--
-- Data for Name: standard; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.standard ("Id", name) FROM stdin;
1	1st Semister
2	2nd Semister
3	3rd Semister
4	4th Semister
5	5th Semister
6	6th Semister
\.


--
-- Data for Name: standardsubject; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.standardsubject ("Id", standard, subject) FROM stdin;
1	1	1
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.student ("Id", name, adhaar, school, standard) FROM stdin;
1	Yusuf	2222-2222-2220	1	1
2	Affan	2222-2222-2221	1	1
\.


--
-- Data for Name: subject; Type: TABLE DATA; Schema: tenanta; Owner: root
--

COPY tenanta.subject ("Id", path, name) FROM stdin;
1	ZY.T01	Operating Systems
\.


--
-- Name: lesson_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lesson_Id_seq"', 1, false);


--
-- Name: lessonsection_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lessonsection_Id_seq"', 5, true);


--
-- Name: lessonsection_fillblanks_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lessonsection_fillblanks_Id_seq"', 1, true);


--
-- Name: lessonsection_lessoninfo_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lessonsection_lessoninfo_Id_seq"', 1, true);


--
-- Name: lessonsection_quiz_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lessonsection_quiz_Id_seq"', 1, true);


--
-- Name: lessonsection_shortquestion_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lessonsection_shortquestion_Id_seq"', 1, true);


--
-- Name: lessonsection_truefalse_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."lessonsection_truefalse_Id_seq"', 1, true);


--
-- Name: logindetail_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."logindetail_Id_seq"', 1, false);


--
-- Name: progress_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."progress_Id_seq"', 1, false);


--
-- Name: school_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."school_Id_seq"', 1, true);


--
-- Name: schoolstandard_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."schoolstandard_Id_seq"', 3, true);


--
-- Name: standard_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."standard_Id_seq"', 1, false);


--
-- Name: standardsubject_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."standardsubject_Id_seq"', 1, true);


--
-- Name: student_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."student_Id_seq"', 2, true);


--
-- Name: subject_Id_seq; Type: SEQUENCE SET; Schema: tenanta; Owner: root
--

SELECT pg_catalog.setval('tenanta."subject_Id_seq"', 1, true);


--
-- Name: lesson lesson_name_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lesson
    ADD CONSTRAINT lesson_name_key UNIQUE (name);


--
-- Name: lesson lesson_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lesson
    ADD CONSTRAINT lesson_path_key UNIQUE (path);


--
-- Name: lesson lesson_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lesson
    ADD CONSTRAINT lesson_pkey PRIMARY KEY ("Id");


--
-- Name: lessonsection lessonsection_fillblanksId_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT "lessonsection_fillblanksId_key" UNIQUE ("fillblanksId");


--
-- Name: lessonsection_fillblanks lessonsection_fillblanks_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_fillblanks
    ADD CONSTRAINT lessonsection_fillblanks_path_key UNIQUE (path);


--
-- Name: lessonsection_fillblanks lessonsection_fillblanks_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_fillblanks
    ADD CONSTRAINT lessonsection_fillblanks_pkey PRIMARY KEY ("Id");


--
-- Name: lessonsection lessonsection_lessoninfoId_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT "lessonsection_lessoninfoId_key" UNIQUE ("lessoninfoId");


--
-- Name: lessonsection_lessoninfo lessonsection_lessoninfo_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_lessoninfo
    ADD CONSTRAINT lessonsection_lessoninfo_path_key UNIQUE (path);


--
-- Name: lessonsection_lessoninfo lessonsection_lessoninfo_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_lessoninfo
    ADD CONSTRAINT lessonsection_lessoninfo_pkey PRIMARY KEY ("Id");


--
-- Name: lessonsection lessonsection_name_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT lessonsection_name_key UNIQUE (name);


--
-- Name: lessonsection lessonsection_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT lessonsection_path_key UNIQUE (path);


--
-- Name: lessonsection lessonsection_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT lessonsection_pkey PRIMARY KEY ("Id");


--
-- Name: lessonsection lessonsection_quizId_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT "lessonsection_quizId_key" UNIQUE ("quizId");


--
-- Name: lessonsection_quiz lessonsection_quiz_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_quiz
    ADD CONSTRAINT lessonsection_quiz_path_key UNIQUE (path);


--
-- Name: lessonsection_quiz lessonsection_quiz_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_quiz
    ADD CONSTRAINT lessonsection_quiz_pkey PRIMARY KEY ("Id");


--
-- Name: lessonsection lessonsection_shortquestionId_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT "lessonsection_shortquestionId_key" UNIQUE ("shortquestionId");


--
-- Name: lessonsection_shortquestion lessonsection_shortquestion_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_shortquestion
    ADD CONSTRAINT lessonsection_shortquestion_path_key UNIQUE (path);


--
-- Name: lessonsection_shortquestion lessonsection_shortquestion_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_shortquestion
    ADD CONSTRAINT lessonsection_shortquestion_pkey PRIMARY KEY ("Id");


--
-- Name: lessonsection lessonsection_truefalseId_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection
    ADD CONSTRAINT "lessonsection_truefalseId_key" UNIQUE ("truefalseId");


--
-- Name: lessonsection_truefalse lessonsection_truefalse_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_truefalse
    ADD CONSTRAINT lessonsection_truefalse_path_key UNIQUE (path);


--
-- Name: lessonsection_truefalse lessonsection_truefalse_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lessonsection_truefalse
    ADD CONSTRAINT lessonsection_truefalse_pkey PRIMARY KEY ("Id");


--
-- Name: logindetail logindetail_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.logindetail
    ADD CONSTRAINT logindetail_pkey PRIMARY KEY ("Id");


--
-- Name: progress progress_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_pkey PRIMARY KEY ("Id");


--
-- Name: school school_name_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.school
    ADD CONSTRAINT school_name_key UNIQUE (name);


--
-- Name: school school_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.school
    ADD CONSTRAINT school_pkey PRIMARY KEY ("Id");


--
-- Name: schoolstandard schoolstandard_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.schoolstandard
    ADD CONSTRAINT schoolstandard_pkey PRIMARY KEY ("Id");


--
-- Name: standard standard_name_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standard
    ADD CONSTRAINT standard_name_key UNIQUE (name);


--
-- Name: standard standard_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standard
    ADD CONSTRAINT standard_pkey PRIMARY KEY ("Id");


--
-- Name: standardsubject standardsubject_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standardsubject
    ADD CONSTRAINT standardsubject_pkey PRIMARY KEY ("Id");


--
-- Name: student student_adhaar_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.student
    ADD CONSTRAINT student_adhaar_key UNIQUE (adhaar);


--
-- Name: student student_name_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.student
    ADD CONSTRAINT student_name_key UNIQUE (name);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.student
    ADD CONSTRAINT student_pkey PRIMARY KEY ("Id");


--
-- Name: subject subject_name_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.subject
    ADD CONSTRAINT subject_name_key UNIQUE (name);


--
-- Name: subject subject_path_key; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.subject
    ADD CONSTRAINT subject_path_key UNIQUE (path);


--
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY ("Id");


--
-- Name: lesson lesson_subject_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.lesson
    ADD CONSTRAINT lesson_subject_fkey FOREIGN KEY (subject) REFERENCES tenanta.subject("Id");


--
-- Name: progress progress_lesson_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_lesson_fkey FOREIGN KEY (lesson) REFERENCES tenanta.lesson("Id");


--
-- Name: progress progress_lessonsection_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_lessonsection_fkey FOREIGN KEY (lessonsection) REFERENCES tenanta.lessonsection("Id");


--
-- Name: progress progress_school_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_school_fkey FOREIGN KEY (school) REFERENCES tenanta.school("Id");


--
-- Name: progress progress_standard_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_standard_fkey FOREIGN KEY (standard) REFERENCES tenanta.standard("Id");


--
-- Name: progress progress_student_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_student_fkey FOREIGN KEY (student) REFERENCES tenanta.student("Id");


--
-- Name: progress progress_subject_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.progress
    ADD CONSTRAINT progress_subject_fkey FOREIGN KEY (subject) REFERENCES tenanta.subject("Id");


--
-- Name: schoolstandard schoolstandard_school_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.schoolstandard
    ADD CONSTRAINT schoolstandard_school_fkey FOREIGN KEY (school) REFERENCES tenanta.school("Id");


--
-- Name: schoolstandard schoolstandard_standard_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.schoolstandard
    ADD CONSTRAINT schoolstandard_standard_fkey FOREIGN KEY (standard) REFERENCES tenanta.standard("Id");


--
-- Name: standardsubject standardsubject_standard_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standardsubject
    ADD CONSTRAINT standardsubject_standard_fkey FOREIGN KEY (standard) REFERENCES tenanta.standard("Id");


--
-- Name: standardsubject standardsubject_subject_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.standardsubject
    ADD CONSTRAINT standardsubject_subject_fkey FOREIGN KEY (subject) REFERENCES tenanta.subject("Id");


--
-- Name: student student_school_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.student
    ADD CONSTRAINT student_school_fkey FOREIGN KEY (school) REFERENCES tenanta.school("Id");


--
-- Name: student student_standard_fkey; Type: FK CONSTRAINT; Schema: tenanta; Owner: root
--

ALTER TABLE ONLY tenanta.student
    ADD CONSTRAINT student_standard_fkey FOREIGN KEY (standard) REFERENCES tenanta.standard("Id");


--
-- PostgreSQL database dump complete
--

\unrestrict BtcAmEdxVpLHtkbRXL6aU79Iax8J5xicBsY2e3xJ3KjCHD4sJj80ZoT92u8UYTy

